#!/bin/bash

CWD=$(pwd) 
backup=~/dotfiles.bak
files="abcde.conf gitconfig gitignore goobookrc tidy.com tmux.conf"

# create backup dir in home dir
echo "Creating $backup for backup of any existing dotfiles in ~"
mkdir -p $backup
echo "...done"

# move any existing dotfiles in homedir to backup directory, then create symlinks 
for file in $files; do
    echo "Moving existing dotfiles from ~ to $backup"
    mv $HOME/.$file $HOME/$backup
    echo "Creating symlink to $file in home directory."
    ln -s $CWD/$file $HOME/.$file
done

printf "\nAll done!"
