#!/usr/bin/env bash

CWD=$(pwd) 
DATE=$(date +"%Y%m%d%H%M")
backup=dotfiles-$DATE
dotfiles="abcde.conf gitconfig gitignore goobookrc screenrc tidy.conf tmux.conf"
configs="newsbeuter ncmpcpp"

# create backup dir in home dir
echo "Creating $backup for backup of any existing files in ~"
mkdir -p $HOME/$backup
echo "...done"

# move any existing dotfiles in ~ to backup directory, then create symlinks 
for dotfile in $dotfiles; do
  echo "Moving existing .$dotfile from ~ to ~/$backup"
  mv $HOME/.$dotfile $HOME/$backup/ > /dev/null 2>&1
  echo "Creating symlink to $dotfile in ~"
  ln -s $CWD/$dotfile $HOME/.$dotfile
done

# one for mailcap for OS X, another for Linux (server)
if [ -f $HOME/.mailcap ]; then
    mv $HOME/.mailcap $HOME/$backup/
fi
if [[ $(uname) == 'Darwin' ]]; then
  ln -s $CWD/mailcap.osx $HOME/.mailcap
else
  ln -s $CWD/mailcap $HOME/.mailcap
fi

# config files
for config in $configs; do
  if [ -d $HOME/.$config ]; then
    mv $HOME/.$config/config $HOME/.$config/config-$DATE > /dev/null 2>&1
    ln -s $CWD/$config.config $HOME/.$config/config
  else
    mkdir $HOME/.$config
    ln -s $CWD/$config.config $HOME/.$config/config
  fi
done

printf "All done!\n"
